name=A3Micro
version=2.0.0
author=R.E Espino (twinsparks.dev)
maintainer=TwinSparks Development
sentence=Arduino library to send messages between A3Micro app and Arduino
paragraph=This is an Arduino library to send messages between A3Micro app and Arduino Uno R3 and R4 boards, using an HM 10 Bluetooth module or the built-in BLE radio of the Uno R4 WiFi. Get the A3 Micro app for Android at a3micro.twinsparks.dev
category=Communication
url=https://a3micro.twinsparks.dev
architectures=*
includes=A3Micro.h
depends=ArduinoBLE
